---
appName: dynamic-reporting
appNamespace: dynamic-reporting
appImage: "registry.linemetrics.dev/linemetrics/frontend-services/in-app-dynamic-reporting"
appTag: edge
imagePullPolicy: "Always"
appReplicas: 3
minReadySeconds: 5
appUpdateStrategy: RollingUpdate

app_restapi_url: "https://restapi.linemetrics.com"