---
include:
  - project: 'LineMetrics/pipeline-components/org/config'
    file: lm_prod_untagged.yml
    # file: lm_default.yml

# Override development-deploy templates
dryrun-deploy-development:
  variables:
    APP_NAME: "dynamic-reporting"
    K3S_CLUSTERNAME: dev-k3s
    K3S_NAMESPACE: "dynamic-reporting"
    K3S_DEPLOY_USER: "dynamic-reporting-user"
    K3S_CLUSTER: "https://192.168.110.11:6445"

deploy-development:
  variables:
    APP_NAME: "dynamic-reporting"
    K3S_CLUSTERNAME: dev-k3s
    K3S_NAMESPACE: "dynamic-reporting"
    K3S_DEPLOY_USER: "dynamic-reporting-user"
    K3S_CLUSTER: "https://192.168.110.11:6445"
  before_script:
    - export APPVERSION=$(cat chart/values.$CI_ENVIRONMENT_NAME.yaml | grep appTag | cut -d' ' -f2)

dryrun-deploy-production:
  variables:
    APP_NAME: "dynamic-reporting"
    K3S_CLUSTERNAME: prod-k3s-lm3
    K3S_NAMESPACE: "dynamic-reporting"
    K3S_DEPLOY_USER: "dynamic-reporting-user"
    K3S_CLUSTER: "https://172.16.1.20:6445"

deploy-production:
  variables:
    APP_NAME: "dynamic-reporting"
    K3S_CLUSTERNAME: prod-k3s-lm3
    K3S_NAMESPACE: "dynamic-reporting"
    K3S_DEPLOY_USER: "dynamic-reporting-user"
    K3S_CLUSTER: "https://172.16.1.20:6445"
  before_script:
    - export APPVERSION=$(cat chart/values.$CI_ENVIRONMENT_NAME.yaml | grep appTag | cut -d' ' -f2)
