services:
  in-app-dynamic-reporting:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  REACT_APP_BASE_URL: "https://restapi.linemetrics.com"
    ports:
      - "1000:80"
    volumes:
      - ./nginx/default_local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config.js_template:/usr/share/nginx/html/apps/config.js:ro
    #environment:
    #  - REACT_APP_BASE_URL=https://rest-api.linemetrics.com