---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName | default "linemetrics" }}"
  namespace: "{{ .Values.appNamespace | default "linemetrics" }}"
spec:
  replicas: {{ .Values.appReplicas | default "3" }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "{{ .Values.appName | default "linemetrics" }}"
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{ .Values.appName | default "linemetrics" }}"
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: "{{ .Values.appName | default "linemetrics" }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy | default "IfNotPresent" }}"
          image: "{{ .Values.appImage | default "linemetrics" }}:{{ .Values.appTag | default "latest" }}"
          ports:
          - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "{{ .Values.appName | default "linemetrics" }}"
            topologyKey: "kubernetes.io/hostname"
